openapi: 3.1.0
info:
  version: 0.1.0
  title: Base Project
  description: Dokumentasi untuk API Base Project
paths:
  /csrf-cookie:
    get:
      summary: Rute dummy untuk set CSRF-TOKEN cookie
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    minimum: 200
                    maximum: 200
                    example: 200
                    type: integer
                  message:
                    example: success
                    type: string
                  data:
                    type: string
                    nullable: true
                    example: null
