definitions:
  responses.GeneralResponse:
    properties:
      code:
        example: 123
        type: integer
      data: {}
      message:
        example: success
        type: string
    type: object
  responses.Role:
    properties:
      is_default:
        type: boolean
      name:
        example: Mahasiswa
        type: string
      permissions:
        items:
          type: string
        type: array
    type: object
  responses.User:
    properties:
      active_role:
        example: Mahasiswa
        type: string
      id:
        example: 00000000-0000-0000-0000-000000000000
        type: string
      roles:
        items:
          $ref: '#/definitions/responses.Role'
        type: array
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: Link login berhasil didapatkan
          schema:
            $ref: '#/definitions/responses.GeneralResponse'
        "500":
          description: Terjadi kesalahan saat menghubungi provider OpenID Connect
          schema:
            $ref: '#/definitions/responses.GeneralResponse'
      security:
      - CSRF Token: []
      summary: Rute untuk mendapatkan link login melalui OpenID Connect
      tags:
      - Authentication & Authorization
  /auth/logout:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: Logout berhasil
          schema:
            allOf:
            - $ref: '#/definitions/responses.GeneralResponse'
            - properties:
                code:
                  type: integer
                data:
                  type: string
                message:
                  type: string
              type: object
      security:
      - Session: []
      summary: Rute untuk logout
      tags:
      - Authentication & Authorization
  /auth/user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Data user berhasil didapatkan
          schema:
            allOf:
            - $ref: '#/definitions/responses.GeneralResponse'
            - properties:
                code:
                  type: integer
                data:
                  allOf:
                  - $ref: '#/definitions/responses.User'
                  - properties:
                      roles:
                        items:
                          $ref: '#/definitions/responses.Role'
                        type: array
                    type: object
                message:
                  type: string
              type: object
      security:
      - Session: []
      summary: Rute untuk mendapatkan data user yang sedang login
      tags:
      - Authentication & Authorization
  /csrf-cookie:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Cookie berhasil diset
          schema:
            allOf:
            - $ref: '#/definitions/responses.GeneralResponse'
            - properties:
                code:
                  type: integer
                message:
                  type: string
              type: object
      summary: Rute dummy untuk set CSRF-TOKEN cookie
      tags:
      - CSRF Protection
securityDefinitions:
  CSRF Token:
    in: header
    name: x-csrf-token
    type: apiKey
  Session:
    in: cookie
    name: akademik_its_ac_id_session
    type: apiKey
swagger: "2.0"
